### ISSUE TITLE
404

### ISSUE THREAD

**Issue by wanghaisheng** [amisadmin/fastapi_amis_admin#20]
/demo (master)$ git pull
$ python demo-model.py 
INFO:     Started server process [23792]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to                  quit)
INFO:     127.0.0.1:13268 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:13268 - "GET /pwabuilder-sw.js HTTP/1.1" 40                     04 Not Found

**Comment by amisadmin** [comment]
- 访问: http://127.0.0.1:8000/admin
- 请查看文档: https://docs.amis.work/

**Comment by wanghaisheng** [comment]
```
$ python demo-simple.py 
INFO:     Started server process [26372]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to                  quit)
INFO:     127.0.0.1:2732 - "GET /admin HTTP/1.1" 307 Temporary                       Redirect
INFO:     127.0.0.1:2732 - "GET / HTTP/1.1" 307 Temporary Redir                     rect
INFO:     127.0.0.1:2732 - "GET /amis.json?_parser=html HTTP/1.1"                   [91m500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\Program Files\anaconda3\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 376, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "D:\Program Files\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "D:\Program Files\anaconda3\lib\site-packages\uvicorn\middleware\debug.py", line 96, in __call__
    raise exc from None
  File "D:\Program Files\anaconda3\lib\site-packages\uvicorn\middleware\debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "D:\Program Files\anaconda3\lib\site-packages\fastapi\applications.py", line 211, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Program Files\anaconda3\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Program Files\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "D:\Program Files\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "D:\Program Files\anaconda3\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "D:\Program Files\anaconda3\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "D:\Program Files\anaconda3\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "D:\Program Files\anaconda3\lib\site-packages\starlette\routing.py", line 408, in handle
    await self.app(scope, receive, send)
  File "D:\Program Files\anaconda3\lib\site-packages\fastapi\applications.py", line 211, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Program Files\anaconda3\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Program Files\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "D:\Program Files\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "D:\Program Files\anaconda3\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "D:\Program Files\anaconda3\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "D:\Program Files\anaconda3\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "D:\Program Files\anaconda3\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "D:\Program Files\anaconda3\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "D:\Program Files\anaconda3\lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "D:\Program Files\anaconda3\lib\site-packages\fastapi\routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\Program Files\anaconda3\lib\site-packages\fastapi_amis_admin\amis_admin\admin.py", line 656, in route
    return self.page_parser(request, page)
  File "D:\Program Files\anaconda3\lib\site-packages\fastapi_amis_admin\amis_admin\admin.py", line 633, in page_parser
    result = page.amis_html(self.template_name)
  File "D:\Program Files\anaconda3\lib\site-packages\fastapi_amis_admin\amis\components.py", line 274, in amis_html
    '[[AmisSchemaJson]]', self.amis_json()
  File "D:\Program Files\anaconda3\lib\site-packages\fastapi_amis_admin\amis\types.py", line 18, in amis_json
    return self.json(exclude_none=True, by_alias=True)
  File "pydantic\main.py", line 490, in pydantic.main.BaseModel.json
TypeError: 'default' is an invalid keyword argument for this function
INFO:     127.0.0.1:2734 - "GET /favicon.ico HTTP/1.1" 404 Not                       Found
```
